### PR TITLE
Test: add Hugging Face Model

### PR DESCRIPTION
**Pull request by cristianoc**
Test adding a Hugging Face Model.
Any ideas on what would be a good model to try?

### CODE REVIEW

**Comment by cristianoc** [comment]
CC @sadiqj

**Comment by jesse-michael-han** [comment]
yeah let's add `camlcoder`! https://huggingface.co/sadiqj/camlcoder

**Comment by sadiqj** [comment]
I'd be happy to help here. @cristianoc did you have any success with this branch? Another option is we try creating a ggml version of camlcoder.

(I have an update of camlcoder in the works that was also trained on dune build files)

**Comment by cristianoc** [comment]
I tried. It could load the model but completion would run and produce nothing while streaming (and no cpu usage).
Without streaming it works.

**Comment by cristianoc** [comment]
Understanding dune files would be sweet. I always have to look things up again every time I want to modify one.

**Comment by EdAyers** [comment]
Hi is this RTM? What are the issues left that need addressing?

**Comment by cristianoc** [comment]
Sure. Just illustrates one hf model.
Adding more can be done separately.

**Comment by cristianoc** [comment]
This got stale.

**Pull request closed without merging**
