### PR TITLE
Portable bundles

### PR DESCRIPTION
**Pull request by JacksonKearl**

### CODE REVIEW

**Comment by cristianoc** [comment]
@JacksonKearl ready to merge?

**Comment by cristianoc** [comment]
There seems to be some leftover `rift-engine/.github` which is not used.

**Comment by JacksonKearl** [comment]
@cristianoc @jesse-michael-han this should be ready for testing, would be great if you could run this branch in dev and see if download flow works on your machines. The "Launch Server" step is a bit slow on the first go but overall the process is ~2x faster than the old flow. 

As for the code change, currently I've synced the vscode version up to to the server version ("v2.1.0-dev" rn), and the github actions are set up to make a build and release every time a tag matching `v` is pushed, which the extension can then download artifacts from. LMK what you think of keeping one "version" for the whole repo. 
https://github.com/morph-labs/rift/releases/tag/v2.1.0-dev

**Comment by jesse-michael-han** [comment]
awesome work 🔥🔥🔥

**Comment by cristianoc** [comment]
@JacksonKearl this is fantastic. Works out of the box.

**Pull request merged**
